services:
  web:
    container_name: CAMERA_Production
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 camera.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    mem_limit: 2G
