# Generated by Django 5.0.3 on 2024-05-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("index", models.CharField(max_length=12)),
                ("time", models.DateTimeField(auto_now=True)),
                ("image_url", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=12)),
                ("enabled", models.BooleanField(default=True)),
                ("video_url", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "cameras",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=45)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=9)),
                ("district", models.IntegerField()),
            ],
            options={
                "db_table": "incidents",
            },
        ),
    ]
